### ISSUE TITLE
Special characters produce a read error on the Notchian Server and Moonpie

### ISSUE THREAD

**Issue by RemineHD** [Stay1444/Moonpie#6]
```Disconnected from server (ReadDataChunk)
[22:48:52 ERR] Error reading packet S2C
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Moonpie.Protocol.Network.InByteBuffer.ReadVarInt() in C:\Users\remin\Documents\GitHub\Moonpie\src\Moonpie\Protocol\Network\InByteBuffer.cs:line 171
   at Moonpie.Protocol.Protocol.PacketMapper.DeserializeS2CPacket(InByteBuffer buffer) in C:\Users\remin\Documents\GitHub\Moonpie\src\Moonpie\Protocol\Protocol\PacketMapper.cs:line 231
   at Moonpie.Protocol.Network.Connection.ReadS2CPacketAsync() in C:\Users\remin\Documents\GitHub\Moonpie\src\Moonpie\Protocol\Network\Connection.cs:line 134
Server disconnected```

**Comment by Stay1444** [comment]
Fixed
